name: Check HCL

on:
  push:
    branches:
      - main

jobs:
  check-hcl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Nomad
        uses: hashicorp/setup-nomad@main

      - name: Fail on malformatted files
        run: |
          EXIT_CODE=0
          while IFS= read -r file; do
            echo "Checking $file"
            if ! nomad fmt -list=false -write=false -check "$file" &>/dev/null ; then
              echo "::error file=$file::File is not properly formatted"
              EXIT_CODE=1
            fi
          done < <(find . -type f -name "*.hcl")
          exit $EXIT_CODE
