name: Format HCL

on:
  push:
    branches:
      - main

jobs:
  format-hcl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format HCL files
        uses: devops-infra/action-format-hcl@master

      - name: Commit changes to repo
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "chore(format):"
          commit_message: "format HCL files"
